export const plans = {
      A: {
        name: "A方案",
        duration: "40分鐘",
        title: "痘粉清潔",
        description:
          "服務流程：胺基酸淨膚泡泡潔面基礎清潔臉部，超聲波將老廢角質淨化，氫氧小氣泡導出粉刺與黑頭，冰肌面膜來舒緩鎮定肌膚。",
        originalPrice: "$850",
        memberPrice: "$550",
        steps: 15,
        stepImages: [
          "a-c-step-01-makeup-removal.png",
          "a-c-step-02-amino-acid-cleansing.png",
          "a-step-03-blackhead-extraction.png",
          "a-step-04-steam-softening.png",
          "a-step-05-hydro-bubble-cleansing.png",
          "a-step-06-ultrasonic-purification.png",
          "a-step-07-berry-aloe-soothing.png",
          "a-step-08-ice-massage.png",
          "a-step-09-chamomile-mask.png",
          "a-step-10-ultrasonic-infusion.png",
          "a-step-11-light-energy-conditioning.png",
          "a-step-12-light-skincare.png",
          "a-step-13-massage-absorption.png",
          "a-step-14-sunscreen-protection.png",
          "a-step-15-daily-care-advice.png",
        ],
        stepNames: [
          "卸妝掃除髒汙",
          "胺基酸泡泡潔面",
          "粉刺導出液",
          "蒸氣軟化角質",
          "氫氧小氣泡清潔毛孔",
          "超聲波淨化角質",
          "莓果蘆薈舒緩",
          "冰肌按摩",
          "洋甘菊面膜潤膚",
          "超音波導入",
          "光感能量調理膚況",
          "輕保養",
          "按摩強化吸收",
          "防曬隔離",
          "給予日常保養建議",
        ],
      },
      B: {
        name: "B方案",
        duration: "50分鐘",
        title: "柔嫩亮膚",
        description:
          "服務流程：胺基酸淨膚泡泡潔面基礎清潔臉部，透過高光波柔嫩提亮肌膚，再使用歐盟認證天然精油按摩提亮。",
        originalPrice: "$1250",
        memberPrice: "$850",
        steps: 15,
        stepImages: [
          "b-c-step-01-makeup-removal.png",
          "b-c-step-02-amino-acid-cleansing.png",
          "b-step-03-blackhead-extraction.png",
          "b-step-04-steam-softening.png",
          "b-step-05-hydro-bubble-cleansing.png",
          "b-step-06-ultrasonic-purification.png",
          "b-step-07-hyaluronic-acid-hydration.png",
          "b-step-08-european-oil-massage.png",
          "b-step-09-chamomile-mask-moisturizing.png",
          "b-step-10-ice-massage.png",
          "b-step-11-light-energy-treatment.png",
          "b-step-12-light-skincare-treatment.png",
          "b-step-13-massage-absorption-enhancement.png",
          "b-step-14-sunscreen-isolation.png",
          "b-step-15-daily-care-consultation.png",
        ],
        stepNames: [
          "卸妝掃除髒汙",
          "胺基酸泡泡潔面",
          "粉刺導出液",
          "蒸氣軟化角質",
          "氫氧小氣泡清潔毛孔",
          "超聲波淨化角質",
          "牛奶肌光感提亮",
          "歐洲植萃精油舒壓按摩",
          "洋甘菊面膜潤膚",
          "冰肌按摩",
          "光感能量調理膚況",
          "輕保養",
          "按摩強化吸收",
          "防曬隔離",
          "給予日常保養建議",
        ],
      },
      C: {
        name: "C方案",
        duration: "60分鐘",
        title: "提拉保濕",
        description:
          "服務流程：胺基酸淨膚泡泡潔面基礎清潔臉部，使用玻尿酸精華透過水光探頭注入肌膚，選用歐盟認證天然精油搭配專業級射頻探頭提拉肌膚。",
        originalPrice: "$1650",
        memberPrice: "$1250",
        steps: 17,
        stepImages: [
          "c-step-01-makeup-removal.png",
          "c-step-02-amino-acid-cleansing.png",
          "c-step-03-blackhead-extraction.png",
          "c-step-04-steam-softening.png",
          "c-step-05-hydro-bubble-cleansing.png",
          "c-step-06-ultrasonic-purification.png",
          "c-step-07-hyaluronic-acid-hydration.png",
          "c-step-08-water-light-gun-brightening.png",
          "c-step-09-european-botanical-massage.png",
          "c-step-12-ice-massage.png",
          "c-step-11-chamomile-mask.png",
          "c-step-12-ice-massage.png",
          "c-step-13-mask-removal.png",
          "c-step-14-light-skincare.png",
          "c-step-15-massage-absorption.png",
          "c-step-16-sunscreen-protection.png",
          "c-step-17-daily-care-advice.png",
        ],
        stepNames: [
          "卸妝掃除髒汙",
          "胺基酸泡泡潔面",
          "粉刺導出液",
          "蒸氣軟化角質",
          "氫氧小氣泡清潔毛孔",
          "超聲波淨化角質",
          "玻尿酸精華補水",
          "水光槍深層透亮",
          "歐洲植萃精油舒壓按摩",
          "專業級射頻探頭提拉",
          "洋甘菊面膜潤膚",
          "冰肌按摩",
          "卸膜",
          "輕保養",
          "按摩強化吸收",
          "防曬隔離",
          "給予日常保養建議",
        ],
      },
      EXOSOME: {
        name: "EXOSOME方案",
        duration: "60分鐘",
        title: "科技逆齡",
        description:
          "服務流程：胺基酸泡泡清潔臉部，透過超聲波與氫氧小氣泡導出粉刺並淨化角質。肌膚深層清潔後，先利用牛奶肌提亮膚色與強化吸收力，再進行外泌體精華搭配電波儀器進行全臉導入拉提，最後使用面膜與鎖水精華完美收尾。",
        originalPrice: "$4480",
        memberPrice: "$2480",
        steps: 17,
        stepImages: [
          "e-step-01-makeup-removal.png",
          "e-step-02-amino-acid-cleansing.png",
          "e-step-03-blackhead-extraction.png",
          "e-step-04-steam-softening.png",
          "e-step-05-hydro-bubble-cleansing.png",
          "e-step-06-ultrasonic-purification.png",
          "e-step-07-hyaluronic-acid-hydration.png",
          "e-step-08-water-light-gun-brightening.png",
          "e-step-09-european-botanical-massage.png",
          "e-step-10-light-energy-conditioning.png",
          "e-step-11-chamomile-mask.png",
          "e-step-12-ice-massage.png",
          "e-step-13-mask-removal.png",
          "e-step-14-light-skincare.png",
          "e-step-15-massage-absorption.png",
          "e-step-16-sunscreen-protection.png",
          "e-step-17-daily-care-advice.png",
        ],
        stepNames: [
          "卸妝掃除髒汙",
          "胺基酸泡泡潔面",
          "粉刺導出液",
          "蒸氣軟化角質",
          "氫氧小氣泡清潔毛孔",
          "超聲波淨化角質",
          "牛奶肌光感保養",
          "外泌體精華EXOSOME",
          "7倍電流緊緻拉提",
          "冰肌按摩",
          "洋甘菊面膜潤膚",
          "超音波導入",
          "卸膜",
          "輕保養",
          "按摩強化吸收",
          "防曬隔離",
          "給予日常保養建議",
        ],
      },
    };
